name: zen_satori
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  go_router: ^17.2.3
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.42
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.15.0
  drift_dev: ^2.31.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/quotes/en/

  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
